bundler_args: --without development doc
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - jruby-9.1.7.0
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
matrix:
  fast_finish: true
sudo: false
